<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLcxhy5x\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLcxhy5x/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLcxhy5x.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLcxhy5x\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLcxhy5x\appProdProjectContainer([
    'container.build_hash' => 'Lcxhy5x',
    'container.build_id' => 'e6d7d9df',
    'container.build_time' => 1762519522,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLcxhy5x');
