<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNjdt9cu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNjdt9cu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNjdt9cu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNjdt9cu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNjdt9cu\appProdProjectContainer([
    'container.build_hash' => 'Njdt9cu',
    'container.build_id' => 'efbd3a3a',
    'container.build_time' => 1762534645,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNjdt9cu');
