<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxtoeyn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxtoeyn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTxtoeyn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTxtoeyn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTxtoeyn\appDevDebugProjectContainer([
    'container.build_hash' => 'Txtoeyn',
    'container.build_id' => '8e206826',
    'container.build_time' => 1762521571,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxtoeyn');
